-- MySQL Script generated by MySQL Workbench
-- Tue 19 Jan 2021 07:15:32 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eduteq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eduteq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eduteq` ;
USE `eduteq` ;

-- -----------------------------------------------------
-- Table `eduteq`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`publicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`division` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NULL,
  `id_division` INT NULL,
  `correo` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_1_idx` (`id_division` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_1`
    FOREIGN KEY (`id_division`)
    REFERENCES `eduteq`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_2`
    FOREIGN KEY (`id_division`)
    REFERENCES `eduteq`.`division` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`tipo_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`tipo_evento` (
  `id` INT NOT NULL,
  `tipo_evento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `tipo_evento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_1_idx` (`id_usuario` ASC, `tipo_evento` ASC) VISIBLE,
  INDEX `fk_eventos_2_idx` (`tipo_evento` ASC) VISIBLE,
  CONSTRAINT `fk_eventos_1`
    FOREIGN KEY (`id_usuario` , `tipo_evento`)
    REFERENCES `eduteq`.`usuario` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_2`
    FOREIGN KEY (`tipo_evento`)
    REFERENCES `eduteq`.`tipo_evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`mercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`mercado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `id_usuario` INT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_producto_1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_venta_producto_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `eduteq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`publicacion_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`publicacion_usuario` (
  `id_usuario` INT NULL,
  `id_publicacion` INT NULL,
  `comentario` VARCHAR(45) NULL,
  INDEX `fk_publicacion_usuario_1_idx` (`id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_publicacion_usuario_1`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `eduteq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicacion_usuario_2`
    FOREIGN KEY ()
    REFERENCES `eduteq`.`publicacion` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`carrera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduteq`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduteq`.`perfil` (
  `id` INT NOT NULL,
  `id_usuario` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `pasatiempos` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `id_carrera` INT NULL,
  `foto_perfil` VARCHAR(45) NULL,
  `edad` INT NULL,
  `id_estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_perfil_2_idx` (`id_carrera` ASC) VISIBLE,
  INDEX `fk_perfil_3_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `eduteq`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_2`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `eduteq`.`carrera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_3`
    FOREIGN KEY (`id_estado`)
    REFERENCES `eduteq`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
